name: Docker Build and Publish

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Images
        run: |
          while read i; do
            docker build -t allthingsnix/minecraft:$i .
          done < build-versions.txt

      - name: DEBUG
        run: |
          docker images